database:
  driver: ""
  # Only the name of the driver (MySQL, MariaDB, SQLite, ...)
  path: ""
  # Syntax: C:/.../ServerFiles/SubFolder1/SubFolder2/..., or SubFolder1/SubFolder2/...
  # Syntax:
  name: ""
  # Without the extension
  username: ""
  password: ""
  tablenames: 
    user: ""
    terminal: ""

initialDeposit: 20.00