name: Sylvarion
version: '${project.version}'
main: com.itsadamly.sylvarion.Sylvarion
api-version: 1.17

commands:
  atm:
    description: Everything about Sylvarion ATM
    usage: "\n/<command> reload\n/<command> open [<player>]\n/<command> close [<player>]\n/<command> checkbalance [<player>]\n/<command> updatebalance <players> (set|add|remove)\n/<command> deposit <player> <amount>\n/<command> withdraw <player> <amount>"


depend:
  - Vault

permissions:
sylv.atm: 
  description: "idk"
  default: notop
sylv.atm.admin:
  description: "select other players in /atm command"
  default: op